- name: variables
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false
  - name: DURATION
    prompt: enter duration
    private: false
  - name: TRAINER
    prompt: enter trainer name
    private: false       
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{COURSE}} , duration is {{DURATION}}, trainer is {{TRAINER}}"